-- 은수 아카이브 기본 보안 정책
-- Supabase 대시보드 > SQL Editor에서 전체를 붙여 넣고 Run을 누르세요.

-- drawings 테이블이 아직 없다면 먼저 생성합니다.
create table if not exists public.drawings (
  id bigint generated by default as identity primary key,
  title text not null,
  date text not null,
  description text,
  category text,
  quote text,
  image_url text not null,
  created_at timestamptz default now()
);

-- 테이블 보호를 켭니다.
alter table public.drawings enable row level security;

-- 기존에 같은 이름의 정책이 있으면 다시 만들 수 있도록 제거합니다.
drop policy if exists "그림은 누구나 볼 수 있음" on public.drawings;
drop policy if exists "로그인한 관리자만 그림 추가" on public.drawings;
drop policy if exists "로그인한 관리자만 그림 수정" on public.drawings;
drop policy if exists "로그인한 관리자만 그림 삭제" on public.drawings;

-- 공개 사이트에서는 그림을 볼 수 있습니다.
create policy "그림은 누구나 볼 수 있음"
on public.drawings for select
to anon, authenticated
using (true);

-- 로그인한 사용자만 추가·수정·삭제할 수 있습니다.
-- auth.uid() is not null은 Supabase 로그인 사용자라는 뜻입니다.
create policy "로그인한 관리자만 그림 추가"
on public.drawings for insert
to authenticated
with check (auth.uid() is not null);

create policy "로그인한 관리자만 그림 수정"
on public.drawings for update
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);

create policy "로그인한 관리자만 그림 삭제"
on public.drawings for delete
to authenticated
using (auth.uid() is not null);

-- Storage에서 eunsu-images 버킷을 먼저 만든 뒤 아래 정책을 실행하세요.
-- 사진은 공개적으로 볼 수 있지만, 업로드·수정·삭제는 로그인 사용자만 가능합니다.
drop policy if exists "사진은 누구나 보기" on storage.objects;
drop policy if exists "로그인한 관리자만 사진 업로드" on storage.objects;
drop policy if exists "로그인한 관리자만 사진 수정" on storage.objects;
drop policy if exists "로그인한 관리자만 사진 삭제" on storage.objects;

create policy "사진은 누구나 보기"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'eunsu-images');

create policy "로그인한 관리자만 사진 업로드"
on storage.objects for insert
to authenticated
with check (bucket_id = 'eunsu-images' and auth.uid() is not null);

create policy "로그인한 관리자만 사진 수정"
on storage.objects for update
to authenticated
using (bucket_id = 'eunsu-images' and auth.uid() is not null)
with check (bucket_id = 'eunsu-images' and auth.uid() is not null);

create policy "로그인한 관리자만 사진 삭제"
on storage.objects for delete
to authenticated
using (bucket_id = 'eunsu-images' and auth.uid() is not null);
